#!/bin/sh
module="altera_dma"
device="altera_dma"
mode="666"

# load the module
/sbin/insmod ./$module.ko $* || exit 1

# remove stale nodes
rm -f /dev/$device

# create new device node
major=`grep -w $module /proc/devices | cut -f1 -d" "`
mknod /dev/$device c $major 0

# change permissions to allow all users to read/write
chmod $mode /dev/$device

# make user program
rm -f ./user/user
gcc ./user/user.c -o ./user/user
