# TCL File Generated by Component Editor 16.0
# Fri Sep 16 17:41:21 PDT 2016
# DO NOT MODIFY


# 
# avalon_bridge "Off-Chip Memory Avalon Bridge" v1.0
#  2016.09.16.17:41:21
# An Avalon bridge to export master/slave port for out-of-system control
# 

# 
# request TCL package from ACDS 16.0
# 
package require -exact qsys 16.0


# 
# module avalon_bridge
# 
set_module_property DESCRIPTION "An Avalon bridge to export master/slave port for out-of-system control"
set_module_property NAME avalon_bridge
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP DCNN
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Off-Chip Memory Avalon Bridge"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_bridge
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_bridge.v VERILOG PATH avalon_bridge.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL avalon_bridge
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_bridge.v VERILOG PATH avalon_bridge.v


# 
# parameters
# 
add_parameter ADDR_WIDTH INTEGER 64
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 64
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter DATA_WIDTH_M INTEGER 64
set_parameter_property DATA_WIDTH_M DEFAULT_VALUE 64
set_parameter_property DATA_WIDTH_M DISPLAY_NAME DATA_WIDTH_M
set_parameter_property DATA_WIDTH_M TYPE INTEGER
set_parameter_property DATA_WIDTH_M UNITS None
set_parameter_property DATA_WIDTH_M ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH_M HDL_PARAMETER true
add_parameter BE_WIDTH_M INTEGER 8
set_parameter_property BE_WIDTH_M DEFAULT_VALUE 8
set_parameter_property BE_WIDTH_M DISPLAY_NAME BE_WIDTH_M
set_parameter_property BE_WIDTH_M TYPE INTEGER
set_parameter_property BE_WIDTH_M UNITS None
set_parameter_property BE_WIDTH_M ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BE_WIDTH_M HDL_PARAMETER true
add_parameter DATA_WIDTH_S INTEGER 64
set_parameter_property DATA_WIDTH_S DEFAULT_VALUE 64
set_parameter_property DATA_WIDTH_S DISPLAY_NAME DATA_WIDTH_S
set_parameter_property DATA_WIDTH_S TYPE INTEGER
set_parameter_property DATA_WIDTH_S UNITS None
set_parameter_property DATA_WIDTH_S ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH_S HDL_PARAMETER true
add_parameter BE_WIDTH_S INTEGER 8
set_parameter_property BE_WIDTH_S DEFAULT_VALUE 8
set_parameter_property BE_WIDTH_S DISPLAY_NAME BE_WIDTH_S
set_parameter_property BE_WIDTH_S TYPE INTEGER
set_parameter_property BE_WIDTH_S UNITS None
set_parameter_property BE_WIDTH_S ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BE_WIDTH_S HDL_PARAMETER true
add_parameter MAX_BSIZE INTEGER 1
set_parameter_property MAX_BSIZE DEFAULT_VALUE 1
set_parameter_property MAX_BSIZE DISPLAY_NAME MAX_BSIZE
set_parameter_property MAX_BSIZE TYPE INTEGER
set_parameter_property MAX_BSIZE UNITS None
set_parameter_property MAX_BSIZE ALLOWED_RANGES -2147483648:2147483647
set_parameter_property MAX_BSIZE HDL_PARAMETER true


# 
# display items
# 


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits WORDS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master avl_master_ready waitrequest_n Input 1
add_interface_port avalon_master avl_master_addr address Output ADDR_WIDTH
add_interface_port avalon_master avl_master_rdata_valid readdatavalid Input 1
add_interface_port avalon_master avl_master_rdata readdata Input DATA_WIDTH_M
add_interface_port avalon_master avl_master_wdata writedata Output DATA_WIDTH_M
add_interface_port avalon_master avl_master_be byteenable Output BE_WIDTH_M
add_interface_port avalon_master avl_master_read_req read Output 1
add_interface_port avalon_master avl_master_write_req write Output 1
add_interface_port avalon_master avl_master_size burstcount Output MAX_BSIZE


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits WORDS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 1
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave avl_slave_read_req read Input 1
add_interface_port avalon_slave avl_slave_write_req write Input 1
add_interface_port avalon_slave avl_slave_ready waitrequest_n Output 1
add_interface_port avalon_slave avl_slave_rdata readdata Output DATA_WIDTH_S
add_interface_port avalon_slave avl_slave_wdata writedata Input DATA_WIDTH_S
add_interface_port avalon_slave avl_slave_be byteenable Input BE_WIDTH_S
add_interface_port avalon_slave avl_slave_rdata_valid readdatavalid Output 1
add_interface_port avalon_slave avl_slave_addr address Input ADDR_WIDTH
add_interface_port avalon_slave avl_slave_size burstcount Input MAX_BSIZE
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0

